# Generated by Django 4.1.5 on 2023-01-24 14:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("transactionsTypes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cnab",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cpf", models.TextField(max_length=11)),
                ("date", models.DateField()),
                ("card", models.TextField(max_length=12)),
                ("time", models.TimeField()),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("owner", models.TextField()),
                ("store", models.TextField()),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cnabs",
                        to="transactionsTypes.type",
                    ),
                ),
            ],
        ),
    ]
