# Generated by Django 4.1.5 on 2023-01-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cnab", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cnab",
            name="type_number",
            field=models.TextField(default=0, max_length=1),
            preserve_default=False,
        ),
    ]
