# Generated by Django 4.1.5 on 2023-01-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=120)),
                (
                    "nature",
                    models.CharField(
                        choices=[("In", "In"), ("Out", "Out")],
                        default="In",
                        max_length=3,
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
