# Generated by Django 4.1.5 on 2023-01-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactionsTypes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="type",
            name="type",
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
